services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${HOST_UID:-1000}
        USER_GID: ${HOST_GID:-1000}
    container_name: code-server
    env_file:
      - .env
    environment:
      TZ: ${TZ:-America/Sao_Paulo}
    ports:
      - "8080:8080"
      - "1455:1455"
    volumes:
      - ../../:/home/coder/workspace
      - ./config:/home/coder/.config/code-server
      - ./data:/home/coder/.local/share/code-server
      - ./dotfiles/.zshrc:/home/coder/.zshrc:ro
      - ./dotfiles/.zprofile:/home/coder/.zprofile:ro
      - ./dotfiles/.p10k.zsh:/home/coder/.p10k.zsh:ro
      - ./dotfiles/.oh-my-zsh:/home/coder/.oh-my-zsh:ro
    restart: unless-stopped
    stop_grace_period: 1m

volumes: {}
