{
 "title": "CURL InfluxDB Metrics",
 "description": "Visualize k6 OSS results stored in InfluxDB",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "InfluxDB", "query": "influxdb" },
   {
    "name": "label",
    "label": "Experiment Label",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"label\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Speed of Download / Upload",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed_download",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "label::tag", "operator": "=~", "value": "/^$label$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed_upload",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "label::tag", "operator": "=~", "value": "/^$label$/" }
     ]
    }
   ]
  },
  {
   "title": "Response time Overview",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "time_namelookup",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "label::tag", "operator": "=~", "value": "/^$label$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "time_appconnect",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "label::tag", "operator": "=~", "value": "/^$label$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "time_connect",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "label::tag", "operator": "=~", "value": "/^$label$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "time_starttransfer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "label::tag", "operator": "=~", "value": "/^$label$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "time_total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "label::tag", "operator": "=~", "value": "/^$label$/" }
     ]
    }
   ]
  },
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "response_code",
     "query": "select COUNT(*) from http_code where (\"label\"::tag =~ /^$label$/) and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "label::tag", "operator": "=~", "value": "/^$label$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Request failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "errormsg",
     "query": "SELECT COUNT(*) FROM http_code WHERE (\"label\"::tag =~ /^$label$/) AND value != 200 AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "label::tag", "operator": "=~", "value": "/^$label$/" }
     ]
    }
   ]
  },
  {
   "title": "Peak RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "response_code",
     "query": "SELECT MEAN(*) AS average_rps FROM ( SELECT COUNT(*) AS rps FROM http_code WHERE (\"label\"::tag =~ /^$label$/) AND $timeFilter GROUP BY time(1s) )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "label::tag", "operator": "=~", "value": "/^$label$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "response_code",
     "query": "select * from time_total where (\"label\"::tag =~ /^$label$/) and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "label::tag", "operator": "=~", "value": "/^$label$/" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "size_download",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}