{
 "title": "Cluster Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_labels, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, node)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\", namespace=~\"$namespace\", node=~\"$node\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sumário Projeto", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quotado Projeto",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "CPU hard quota"
    }
   ]
  },
  {
   "title": "Quota Disponivel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"}) - sum(kube_resourcequota_usage_cpu_cores{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "CPU disponível"
    }
   ]
  },
  {
   "title": "Memória RSS Utilizada",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Memória em uso"
    }
   ]
  },
  {
   "title": "Quota Usada",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_resourcequota_usage_cpu_cores{cluster=~\"$cluster\", namespace=~\"$namespace\"}) / (sum(kube_resourcequota{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\"})) * 100",
     "legendFormat": "Uso de CPU (%)"
    }
   ]
  },
  {
   "title": "Pods Em Execução",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\", namespace=~\"$namespace\", phase=\"Running\"})",
     "legendFormat": "Pods em execução"
    }
   ]
  },
  {
   "title": "Quantidade de Restarts Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Total restarts"
    }
   ]
  },
  {
   "title": "CPU Utilizada",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "CPU total"
    }
   ]
  },
  {
   "title": "Memória Utilizada",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Memória total"
    }
   ]
  },
  {
   "title": "Estado dos Pods",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (phase)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "_Total"
    }
   ]
  },
  {
   "title": "Quantidade de OOM por containers",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, pod, container, node) (\n  kube_pod_container_status_last_terminated_reason{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", reason=\"OOMKilled\"}\n  * on (cluster, namespace, pod) group_left(node)\n    kube_pod_info{cluster=~\"$cluster\", namespace=~\"$namespace\", node=~\"$node\", pod=~\"$pod\"}\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Estado dos Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (phase)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "_Total"
    }
   ]
  },
  {
   "title": "Pods Not Running",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\", namespace=~\"$namespace\", phase!=\"Running\"}) by (pod, phase) > 0",
     "legendFormat": "{{pod}} - {{phase}}"
    }
   ]
  },
  { "title": "Requisições HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Requests por segundo",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests 2xx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\", code=~\"2..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests 5xx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\", code=~\"5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests 4xx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\", code=~\"4..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requisições",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\", code=~\"2..\"}[5m]))",
     "legendFormat": "Status Code 2xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\", code=~\"3..\"}[5m]))",
     "legendFormat": "Status Code 3xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\", code=~\"4..\"}[5m]))",
     "legendFormat": "Status Code 4xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\", code=~\"5..\"}[5m]))",
     "legendFormat": "Status Code 5xx"
    }
   ]
  },
  {
   "title": "Ofensores - Erros",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(apiserver_request_total{cluster=~\"$cluster\", code=~\"4..|5..\"}[5m])) by (code, verb, resource))"
    }
   ]
  },
  {
   "title": "Média Tempo Resposta - POD",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{cluster=~\"$cluster\"}[5m])) by (le, verb)) * 1000",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Média Tempo Resposta - Aplicação",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(apiserver_request_duration_seconds_bucket{cluster=~\"$cluster\"}[5m])) by (le, resource)) * 1000",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "Consumo Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Utilização de Memória por Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace, pod, cluster)",
     "legendFormat": "{{pod}} [{{cluster}}]"
    }
   ]
  },
  {
   "title": "Utilização de CPU por Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod, cluster)",
     "legendFormat": "{{pod}} [{{cluster}}]"
    }
   ]
  },
  {
   "title": "Consumo de Memória por Pod",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod, cluster)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\", unit=\"byte\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod, cluster) / on (pod, cluster) sum(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"memory\", unit=\"byte\", pod=~\"$pod\"}) by (pod, cluster) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Consumo de CPU por Pod",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod, cluster), \"pods\", \"$1\", \"pod\", \"(.*)\")"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\", unit=\"core\", pod=~\"$pod\"}) by (pod, cluster)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod, cluster) / on (pod, cluster) sum(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\", unit=\"core\", pod=~\"$pod\"}) by (pod, cluster) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Network Trasmit - Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Receiver - Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Container Image", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Container Image",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (container, image, pod)"
    }
   ]
  },
  { "title": "Pods por Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Pods por Node",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=~\"$cluster\", namespace=~\"$namespace\", node=~\"$node\"}) by (cluster, node, pod, pod_ip, host_ip)"
    }
   ]
  }
 ]
}