{
 "title": "Fake Metrics Observability",
 "tags": [
  "observability",
  "fake-metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total de Métricas Fake",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (__name__) ({__name__=~\"fake_.*\"}))"
    }
   ]
  },
  {
   "title": "Séries temporais geradas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (__name__) ({__name__=~\"fake_.*\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Logs do Fake Metrics Generator",
   "type": "logs",
   "gridPos": { "h": 15, "w": 18, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{container=\"fake-metrics-generator\"}"
    }
   ]
  }
 ]
}