server:
  http_listen_port: 3101
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: podman-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: podman
          __path__: /var/lib/containers/storage/overlay-containers/*/userdata/ctr.log

    pipeline_stages:
      - cri: {}
      - regex:
          source: filename
          expression: '.*/overlay-containers/(?P<container_id>[^/]+)/userdata/ctr\.log'

      - labels:
          container_id