global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: k8s-fakeMetrics
    metrics_path: /metrics
    static_configs:
      - targets:
          - k8s-fakeMetrics:5500
