services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    command: [
      "--innodb-buffer-pool-size=1G",
      "--bulk_insert_buffer_size=256M",
      "--innodb-flush-log-at-trx-commit=2",
      "--sync_binlog=0"
    ]

  adminer:
    image: adminer:latest
    container_name: adminer_ui
    ports:
      - "8080:8080"
    depends_on:
      - db
