global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: fake-metrics-generator
    metrics_path: /metrics
    static_configs:
      - targets:
          - fake-metrics-generator:5001
