apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  isDefault: true
  editable: true
  jsonData:
    timeInterval: "5s"
  version: 1

- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  database: metrics
  user: ${INFLUXDB_ADMIN_USER}
  password: ${INFLUXDB_ADMIN_PASSWORD}
  isDefault: false
  jsonData:
    httpMode: POST
